name: Deploy

on:
  push:
    branches:
      - master

jobs:
  autotagging:
    name: Add release Tags
    steps:
    - uses: actions/checkout@master
    - uses: jaliborc/action-general-autotag@1.0.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source_file: src/luke/__init__.py
        extraction_regex: "^__version__\\s*=\\s*\"(\\d[\\d\\.]+)\""
        tag_message: "Alpha Release"
  documentation:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/build-documentation
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
          BUILD_DIR: ./docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
